version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: tsapp_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: tsmanager_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - traefik
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
      start_period: 20s

  tsapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tsapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tsapp.rule=Host(`dayan3.devtscape.org`)"
      - "traefik.http.routers.tsapp.entrypoints=websecure"
      - "traefik.http.routers.tsapp.tls.certresolver=myresolver" # Replace 'myresolver' with your Traefik generic resolver, or remove line if using wildcard
      - "traefik.http.services.tsapp.loadbalancer.server.port=8080"
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true

volumes:
  db_data:
